apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-demo
spec:
  replicas: 2

  selector:
    matchLabels:
      app: jenkins-demo

  template:
    metadata:
      labels:
        app: jenkins-demo

    spec:
      containers:
        - name: jenkins-demo
          image: IMAGE_PLACEHOLDER
          ports:
            - containerPort: 8080
